routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

$user_registration = user_registration();

Auth::routes(['verify' => true, 'register' => $user_registration]);

// Socialite routes
Route::group(['namespace' => 'Auth', 'middleware' => 'guest'], function () {
    Route::get('login/{provider}', ['as' => 'social.login', 'uses' => 'LoginController@redirectToProvider']);
    Route::get('login/{provider}/callback', 'LoginController@handleProviderCallback');
});

// Atom/ RSS Feed Routes
Route::feeds();


/*
*
* Frontend Routes
*
* --------------------------------------------------------------------
*/
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    // Route::get('view_prayer_requests', 'FrontendController@view_prayer_requests')->name('view_prayer_requests');
    // Route::get('view_praies', 'FrontendController@view_praies')->name('view_praies');
    // Route::get('pray_for_me_request', 'FrontendController@pray_for_me_request')->name('pray_for_me_request');
    // Route::get('contact_us', 'FrontendController@contact_us')->name('contact_us');
    // Route::get('inspiration', 'FrontendController@inspiration')->name('inspiration');

    Route::group(['middleware' => ['auth']], function () {
        /*
        *
        *  Users Routes
        *
        * ---------------------------------------------------------------------
        */
        Route::get('/', 'FrontendController@index')->name('index');
        Route::post('patient/detail', 'FrontendController@patient_detail')->name('patient.detail');
        Route::get('room/join/{roomName}', 'FrontendController@joinRoom');
        Route::post('room/create', 'FrontendController@createRoom')->name('room.create');
        Route::post('room/sendSMS', 'FrontendController@sendSMS')->name('room.sendSMS');
        $module_name = 'users';
        $controller_name = 'UserController';
        // Route::get("$module_name/{id}", ['as' => "$module_name.show", 'uses' => "$controller_name@show"]);
        Route::get("profile/{id}", ['as' => "$module_name.profile", 'uses' => "$controller_name@profile"]);
        Route::get('profile/{id}/edit', ['as' => "$module_name.profileEdit", 'uses' => "$controller_name@profileEdit"]);
        Route::patch('profile/{id}/edit', ['as' => "$module_name.profileUpdate", 'uses' => "$controller_name@profileUpdate"]);
        Route::get("$module_name/emailConfirmationResend/{id}", ['as' => "$module_name.emailConfirmationResend", 'uses' => "$controller_name@emailConfirmationResend"]);
        Route::get("profile/changePassword/{username}", ['as' => "$module_name.changePassword", 'uses' => "$controller_name@changePassword"]);
        Route::patch("profile/changePassword/{username}", ['as' => "$module_name.changePasswordUpdate", 'uses' => "$controller_name@changePasswordUpdate"]);
        Route::delete('users/userProviderDestroy', ['as' => 'users.userProviderDestroy', 'uses' => 'UserController@userProviderDestroy']);
    });
});

/*
*
* Backend Routes
* These routes need view-backend permission
* --------------------------------------------------------------------
*/
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'backend.', 'middleware' => ['auth', 'can:view_backend']], function () {

    /**
     * Backend Dashboard
     * Namespaces indicate folder structure.
     */
    Route::get('/', 'BackendController@index')->name('home');
    Route::get('dashboard', 'BackendController@index')->name('dashboard');

    /*
     *
     *  Settings Routes
     *
     * ---------------------------------------------------------------------
     */
    Route::group(['middleware' => ['permission:edit_settings']], function () {
        $module_name = 'settings';
        $controller_name = 'SettingController';
        Route::get("$module_name", "$controller_name@index")->name("$module_name");
        Route::post("$module_name", "$controller_name@store")->name("$module_name.store");
    });

    /*
    *
    *  Notification Routes
    *
    * ---------------------------------------------------------------------
    */
    $module_name = 'notifications';
    $controller_name = 'NotificationsController';
    Route::get("$module_name", ['as' => "$module_name.index", 'uses' => "$controller_name@index"]);
    Route::get("$module_name/markAllAsRead", ['as' => "$module_name.markAllAsRead", 'uses' => "$controller_name@markAllAsRead"]);
    Route::delete("$module_name/deleteAll", ['as' => "$module_name.deleteAll", 'uses' => "$controller_name@deleteAll"]);
    Route::get("$module_name/{id}", ['as' => "$module_name.show", 'uses' => "$controller_name@show"]);

    /*
    *
    *  Backup Routes
    *
    * ---------------------------------------------------------------------
    */
    $module_name = 'backups';
    $controller_name = 'BackupController';
    Route::get("$module_name", ['as' => "$module_name.index", 'uses' => "$controller_name@index"]);
    Route::get("$module_name/create", ['as' => "$module_name.create", 'uses' => "$controller_name@create"]);
    Route::get("$module_name/download/{file_name}", ['as' => "$module_name.download", 'uses' => "$controller_name@download"]);
    Route::get("$module_name/delete/{file_name}", ['as' => "$module_name.delete", 'uses' => "$controller_name@delete"]);

    /*
    *
    *  Roles Routes
    *
    * ---------------------------------------------------------------------
    */
    $module_name = 'roles';
    $controller_name = 'RolesController';
    Route::resource("$module_name", "$controller_name");

    /*
    *
    *  Users Routes
    *
    * ---------------------------------------------------------------------
    */
    $module_name = 'users';
    $controller_name = 'UserController';
    Route::get("$module_name/profile/{id}", ['as' => "$module_name.profile", 'uses' => "$controller_name@profile"]);
    Route::get("$module_name/profile/{id}/edit", ['as' => "$module_name.profileEdit", 'uses' => "$controller_name@profileEdit"]);
    Route::patch("$module_name/profile/{id}/edit", ['as' => "$module_name.profileUpdate", 'uses' => "$controller_name@profileUpdate"]);
    Route::get("$module_name/emailConfirmationResend/{id}", ['as' => "$module_name.emailConfirmationResend", 'uses' => "$controller_name@emailConfirmationResend"]);
    Route::delete("$module_name/userProviderDestroy", ['as' => "$module_name.userProviderDestroy", 'uses' => "$controller_name@userProviderDestroy"]);
    Route::get("$module_name/profile/changeProfilePassword/{id}", ['as' => "$module_name.changeProfilePassword", 'uses' => "$controller_name@changeProfilePassword"]);
    Route::patch("$module_name/profile/changeProfilePassword/{id}", ['as' => "$module_name.changeProfilePasswordUpdate", 'uses' => "$controller_name@changeProfilePasswordUpdate"]);
    Route::get("$module_name/changePassword/{id}", ['as' => "$module_name.changePassword", 'uses' => "$controller_name@changePassword"]);
    Route::patch("$module_name/changePassword/{id}", ['as' => "$module_name.changePasswordUpdate", 'uses' => "$controller_name@changePasswordUpdate"]);
    Route::get("$module_name/trashed", ['as' => "$module_name.trashed", 'uses' => "$controller_name@trashed"]);
    Route::patch("$module_name/trashed/{id}", ['as' => "$module_name.restore", 'uses' => "$controller_name@restore"]);
    Route::get("$module_name/index_data", ['as' => "$module_name.index_data", 'uses' => "$controller_name@index_data"]);
    Route::get("$module_name/index_list", ['as' => "$module_name.index_list", 'uses' => "$controller_name@index_list"]);
    Route::resource("$module_name", "$controller_name");
    Route::patch("$module_name/{id}/block", ['as' => "$module_name.block", 'uses' => "$controller_name@block", 'middleware' => ['permission:block_users']]);
    Route::patch("$module_name/{id}/unblock", ['as' => "$module_name.unblock", 'uses' => "$controller_name@unblock", 'middleware' => ['permission:block_users']]);
});

app/Http/Controllers/Frontend/FrontendController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use GuzzleHttp\Client as GClient;
use Illuminate\Http\Request;
use IlluminateHttpRequest;
// use TwilioRestClient;
// use TwilioJwtAccessToken;
// use TwilioJwtGrantsVideoGrant;
use Twilio\Rest\Client;
use Twilio\Jwt\AccessToken;
use Twilio\Jwt\Grants\VideoGrant;
use App\Models\Communityusers;
use App\Models\Patients;
use App\Models\Tasks;

class FrontendController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    protected $sid;
    protected $token;
    protected $key;
    protected $secret;

    public function __construct()
    {
       $this->sid = config('services.twilio.sid');
       $this->token = config('services.twilio.token');
       $this->key = config('services.twilio.key');
       $this->secret = config('services.twilio.secret');
    }

    public function index()
    {
        $body_class = '';
        $user_id = auth()->user()->id;
        $patients = Communityusers::patientGroup(1);
        $tasks = Tasks::physicanTask($user_id);

        // $rooms = [];
        //    try {
        //        $client = new Client($this->sid, $this->token);
        //        $allRooms = $client->video->rooms->read([]);

        //         $rooms = array_map(function($room) {
        //            return $room->uniqueName;
        //         }, $allRooms);

        //    } catch (Exception $e) {
        //        echo "Error: " . $e->getMessage();
        //    }
        
        return view('frontend.index', compact('body_class', 'patients', 'tasks'));
    }

    public function createRoom(Request $request)
    {
        $body_class = '';
        $user_id = auth()->user()->id;
        $patients = Communityusers::patientGroup(1);
        $tasks = Tasks::physicanTask($user_id);

       $client = new Client($this->sid, $this->token);
       $exists = $client->video->rooms->read([ 'uniqueName' => $request->roomName]);

       if (empty($exists)) {
           $client->video->rooms->create([
               'uniqueName' => $request->roomName,
               'type' => 'group',
               'recordParticipantsOnConnect' => false
           ]);
       }
       
       $roomName = $request->roomName;
 
       $identity = auth()->user()->first_name;
       $token = new AccessToken($this->sid, $this->key, $this->secret, 3600, $identity);

       $videoGrant = new VideoGrant();
       $videoGrant->setRoom($roomName);

       $token->addGrant($videoGrant);
       $accessToken = $token->toJWT();
       return view('frontend.index', compact('body_class', 'accessToken', 'patients', 'tasks', 'roomName'));
    }

    public function patient_detail(Request $request) {
        $patient_id = $request->patientId;
        $patient_detail = Patients::find($patient_id);
        return $patient_detail;
    }

    public function sendSMS(Request $request) {
        $message  = $request->input('message');
        $to = $request->input('phoneNum');
         
        $twilioNumber = env('TWILIO_NUMBER');
        
        // $to = '312-273-8058';
        $twilio = new Client($this->sid, $this->token);
        $status = false;
        $result = '';
        // try {
        //     $client->messages->create(
        //         $to,
        //         [
        //             "body" => $message,
        //             "from" => $twilioNumber
        //         ]
        //     );
           
        //     $status = true;
        //     $result = 'Message sent to ' . $to;
        // } catch (TwilioException $e) {
        //     $result = 'Twilio replied with: ' . $e;
        // }
        $service = $twilio->chat->v2->services("ISXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX")
                            ->update(array(
                                         "notificationsAddedToChannelEnabled" => True,
                                         "notificationsAddedToChannelSound" => "default",
                                         "notificationsAddedToChannelTemplate" => "A New message from ${twilioNumber}: ${message}"
                                     )
                            );

        dd($service->friendlyName);
        return ['status'=>$status, 'result'=>$result];
    }
}

resources/views/frontend/contact_us.blade.php
@extends('frontend.layouts.frontend')

@section('title')
{{app_name()}}
@endsection
@section('before-styles')
    <!-- <link rel="stylesheet" href="{{asset('css/frontend/index.css')}}"> -->
@endsection
@section('content')

@endsection

resources/views/frontend/index.blade.php
 
@extends('frontend.layouts.frontend')

@section('title')
{{app_name()}}
@endsection
@section('style')
  <link rel="stylesheet" href="{{asset('css/frontend/calendar.css')}}" />
  @if(isset($accessToken))
  <script src="//media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js"></script>
<script>
	function participantConnected(participant) {
	   console.log('Participant "%s" connected', participant.identity);

	   const div = document.createElement('div');
	   div.id = participant.sid;
	   div.setAttribute("style", "float: left; margin: 10px;");
	   div.innerHTML = "<div style='clear:both'>"+participant.identity+"</div>";

	   participant.tracks.forEach(function(track) {
	       trackAdded(div, track)
	   });

	   participant.on('trackAdded', function(track) {
	       trackAdded(div, track)
	   });
	   participant.on('trackRemoved', trackRemoved);

	   document.getElementById('media-div').appendChild(div);
	}

	function participantDisconnected(participant) {
	   console.log('Participant "%s" disconnected', participant.identity);

	   participant.tracks.forEach(trackRemoved);
	   document.getElementById(participant.sid).remove();
	}

	function trackAdded(div, track) {
	   div.appendChild(track.attach());
	   var video = div.getElementsByTagName("video")[0];
	   if (video) {
	       video.setAttribute("style", "max-width:300px;");
	   }
	}

	function trackRemoved(track) {
	   track.detach().forEach( function(element) { element.remove() });
	}

    Twilio.Video.createLocalTracks({
       audio: true,
       video: { width: 300 }
    }).then(function(localTracks) {
       return Twilio.Video.connect('{{ $accessToken }}', {
           name: '{{ $roomName }}',
           tracks: localTracks,
           video: { width: 300 }
       });
    }).then(function(room) {
       console.log('Successfully joined a Room: ', room.name);

       room.participants.forEach(participantConnected);

       var previewContainer = document.getElementById(room.localParticipant.sid);
       if (!previewContainer || !previewContainer.querySelector('video')) {
           participantConnected(room.localParticipant);
       }

       room.on('participantConnected', function(participant) {
           console.log("Joining: '"+participant.identity+"'");
           participantConnected(participant);
       });

       room.on('participantDisconnected', function(participant) {
           console.log("Disconnected: '"+participant.identity+"'");
           participantDisconnected(participant);
       });
    });
    // additional functions will be added after this point
</script>
@endif
@endsection
@section('content')
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-default elevation-4" style="background: white;">
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 mb-3 d-flex">
            <!-- SEARCH FORM -->
        <form class="form-inline ml-3">
          <div class="input-group input-group-sm frm">
            <input class="form-control form-control-navbar" type="search" placeholder="Patients Search" aria-label="Search" style="border: none; background: none;">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
              <p class="ml-2" style="border-bottom: 1px solid ">
                Recent Patients
              </p>
          </li>
          @if(is_array($patients) && count($patients)>0)
          <select class="form-control" id="patientsList">
            <option></option>
            @foreach($patients as $patient)
            @if($patient['userId'] && $patient['first_name'])  
            <option value="{{$patient['userId']}}">
              {{isset($patient['first_name']) ? $patient['first_name'] : ''}} {{isset($patient['last_name']) ? $patient['last_name'] : ''}}
            </option>
            @endif
            @endforeach
          </select>
          @endif
          <br>
          <div id="current_patient"></div>
         
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="background: white;">
   <br/>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-4 col-md-12 mt-2">
            <!-- small box -->
            <div class="small-box box_shado bg-white">
              <div class="inner">
                <p class="text-center" style="color:#397EE3 !important;"> Most Recent </p>
               <center> <img src="{{asset('frontend/img/happy.png')}}" alt="HappyImage" class="img-fluid py-3" style="margin:-10px 0px;width: 50%;text-align:center;"></center>
                <p class="text-center mt-2"> I've excercised 3 days in a row so far</p>
              </div>
            </div>
             <div class="small-box box_shado bg-white">
              <div class="inner">
                <p class="text-center">Schedule Teleme Visit</p>
                <!-- <img src="{{asset('frontend/img/schedule.png')}}" alt="Schedule Time" class="img-fluid" style="-10px 0px;padding: 3px 18px;"> -->
                <div class="elegant-calencar">
       <p id="reset">reset</p>
        <div id="header" class="clearfix">
           <div class="pre-button"><</div>
            <div class="head-info">
                <div class="head-day"></div>
                <div class="head-month"></div>
            </div>
            <div class="next-button">></div>
        </div>
        <table id="calendar">
            <thead>
                <tr>
                    <th>Sun</th>
                    <th>Mon</th>
                    <th>Tue</th>
                    <th>Wed</th>
                    <th>Thu</th>
                    <th>Fri</th>
                    <th>Sat</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>

                <a href="#" class="btn btn-primary btn-block" style="margin: 18px 0px; border-radius: 30px;color:white !important;">
                 Set Appointment
                </a>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-4 col-md-12">
            <!-- small box -->
            <div class="small-box customSmallBox bg-white ">
              <div class="inner">
                @if(!isset($accessToken))
                <center>
                  <img src="{{asset('frontend/img/mask.png')}}" alt="Mask Group" class="img-fluid">
                </center>
                @else
                <div class="content">
                  <div class="title m-b-md">
                      Video Chat Rooms
                  </div>

                  <div id="media-div">
                  </div>
              </div>
              @endif
              </div>
            </div>
          </div>
          <!-- ./col -->

         <!-- ./col -->
          <div class="col-lg-4 col-md-12">
            <!-- small box -->
            <p class="ml-2" style="border-bottom: 1px solid ">
                My tasks
              </p>
            <div class="small-box customSmallBox bg-white">
              <div class="inner">
                <!-- <img src="{{asset('frontend/img/goal.png')}}" alt="Mask Group" class="img-fluid box_shado b"> -->
                  <ul>
                    @foreach($tasks as $task)
                    <li>
                        {{ $task->name }}
                        <p>{{ $task->description }}</p>
                    </li>
                    @endforeach
                  </ul>
              </div>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
  <div class="content">
   <div class="title m-b-md">
       Video Chat Rooms
   </div>
 
</div>

<form action="{{route('frontend.room.create')}}" method="post" id="room_create">
  {{csrf_field()}}
  <input type="hidden" id="userId" name="userId" />
  <input type="hidden" id="VroomName" name="roomName">
</form>

@endsection
@section('scripts')
<script src="{{asset('js/frontend/calendar.js')}}"></script>
<script>
  $(document).on('click', '.startVideoCall', function(){
     var submitForm = $('#room_create')
     submitForm.submit()
  })
</script>
<script>
  $('#patientsList').change(function() {
     var patientId = $(this).val()
     // var message  = $('#sms_msg').text()
     $.ajax({
       type:'POST',
       url:"{{ route('frontend.patient.detail')}}",
       data:{'patientId': patientId },
       success:function(data){
         // if(data.status) {
          $('#userId').val(data.id)
          $('#VroomName').val('TESTROOM-'+data.id)
          var patientEmail = data.email;
          var patientFirstName = data.first_name;
          var patientLastName = data.last_name;
          var patientPhone = data.phone_number;
          var patientId = data.id;
          var html = '<li class="PatientsName">'
          html += '<p class="mari">'+patientFirstName+' '+patientLastName+'</p>'
          html += '<p> Patient Phone: '+patientPhone+'</p>'
          html += '<p> Patient ID: 393H-R44H-'+patientId+'</p>'
          html += '<div class="row"><div class="col-md-6"><button class="btn btn-primary PatientAppointmentBtn startVideoCall" id="'+patientId+'">'
          html += 'Create An Appointment</button></div>'
          // <div class="col-md-6">'
          // html += '<button class="PatientSmsBtn PatientAppointmentBtn" id="p-'+patientId+'" data-phone="'+patientPhone+'">'
          // html += '<i class="fas fa-tv"></i>Send Notification</button></div></div>'
          html += '</li>'
          $('#current_patient').html(html)
       }
     })
  })
</script>
<script type="text/javascript">
    // $(function () {
    //     $('#appointmentCalendar').datetimepicker({
    //         inline: true,
    //         sideBySide: true
    //     });
    // });
</script>
@endsection

resources/views/frontend/privecy.blade.php
@extends('frontend.layouts.app')

@section('title')
Privacy Policy - {{ config('app.name') }}
@endsection

@section('content')

@endsection

resources/views/frontend/room.blade.php
@extends('frontend.layouts.frontend')

@section('title')
{{app_name()}}
@endsection
@section('styles')
    <!-- <link rel="stylesheet" href="{{asset('css/frontend/index.css')}}"> -->
<script src="//media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js"></script>
<script>
	function participantConnected(participant) {
	   console.log('Participant "%s" connected', participant.identity);

	   const div = document.createElement('div');
	   div.id = participant.sid;
	   div.setAttribute("style", "float: left; margin: 10px;");
	   div.innerHTML = "<div style='clear:both'>"+participant.identity+"</div>";

	   participant.tracks.forEach(function(track) {
	       trackAdded(div, track)
	   });

	   participant.on('trackAdded', function(track) {
	       trackAdded(div, track)
	   });
	   participant.on('trackRemoved', trackRemoved);

	   document.getElementById('media-div').appendChild(div);
	}

	function participantDisconnected(participant) {
	   console.log('Participant "%s" disconnected', participant.identity);

	   participant.tracks.forEach(trackRemoved);
	   document.getElementById(participant.sid).remove();
	}

	function trackAdded(div, track) {
	   div.appendChild(track.attach());
	   var video = div.getElementsByTagName("video")[0];
	   if (video) {
	       video.setAttribute("style", "max-width:300px;");
	   }
	}

	function trackRemoved(track) {
	   track.detach().forEach( function(element) { element.remove() });
	}

    Twilio.Video.createLocalTracks({
       audio: true,
       video: { width: 300 }
    }).then(function(localTracks) {
       return Twilio.Video.connect('{{ $accessToken }}', {
           name: '{{ $roomName }}',
           tracks: localTracks,
           video: { width: 300 }
       });
    }).then(function(room) {
       console.log('Successfully joined a Room: ', room.name);

       room.participants.forEach(participantConnected);

       var previewContainer = document.getElementById(room.localParticipant.sid);
       if (!previewContainer || !previewContainer.querySelector('video')) {
           participantConnected(room.localParticipant);
       }

       room.on('participantConnected', function(participant) {
           console.log("Joining: '"+participant.identity+"'");
           participantConnected(participant);
       });

       room.on('participantDisconnected', function(participant) {
           console.log("Disconnected: '"+participant.identity+"'");
           participantDisconnected(participant);
       });
    });
    // additional functions will be added after this point
</script>

@endsection
@section('content')
<div class="content-wrapper">
 <div class="content">
       <div class="title m-b-md">
           Video Chat Rooms
       </div>

       <div id="media-div">
       </div>
   </div>
</div>
@endsection

resources/views/frontend/terms.blade.php
@extends('frontend.layouts.app')

@section('title')
Terms &amp; Conditions - {{ config('app.name') }}
@endsection

@section('content')
<div class="page-header page-header-small clear-filter" filter-color="orange">
    <div class="page-header-image" data-parallax="true" style="background-image:url('{{asset('img/cover-01.jpg')}}');">
    </div>
    <div class="container">
        <h3 class="title">
            Terms &amp; Conditions - {{ config('app.name') }}
        </h3>
    </div>
</div>

<div class="section">
    <div class="container text-center">
        <strong>Terms &amp; Conditions</strong>
    </div>
</div>

@endsection